#! /bin/sh
. "${HOME}/.cache/wal/colors.sh"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config border_width         1
bspc config window_gap          12
#BW=3
bspc config border_width 3
bspc config window_gap 6
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_action2 resize_corner

bspc rule -a Thunar state=floating
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom -b --experimental-backends &
#wmname LG3D
feh --bg-scale Downloads/7731799.png
mpc random on &
$HOME/.config/polybar/launch.sh 
